# Generated by Django 5.2.8 on 2025-11-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_problem_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
