# Generated by Django 5.2.9 on 2025-12-26 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_alter_problem_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='created_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='code',
            field=models.TextField(default='No Code'),
        ),
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(default='Python', max_length=50),
        ),
        migrations.AddField(
            model_name='submission',
            name='memory',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Running'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('CE', 'Compile Error'), ('RE', 'Runtime Error')], default='P', max_length=3),
        ),
        migrations.AddField(
            model_name='submission',
            name='time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(upload_to='testcases/input')),
                ('output_file', models.FileField(upload_to='testcases/output')),
                ('is_sample', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='problems.problem')),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
