# Generated by Django 5.2.9 on 2025-12-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_alter_problem_created_by_alter_submission_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Running'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('CE', 'Compile Error'), ('RE', 'Runtime Error'), ('IE', 'Internal Error')], default='P', max_length=3),
        ),
    ]
