# Generated by Django 5.2.8 on 2025-12-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_alter_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='passed_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='total_cases',
            field=models.IntegerField(default=0),
        ),
    ]
